require "Scripts.DataConverters.Animation.AnimatorDataConverter"
require "Scripts.DataConverters.Input.KeyboardActivatorDataConverter"
require "Scripts.DataConverters.Input.KeyboardVisibilityDataConverter"
require "Scripts.DataConverters.Physics.EllipseColliderDataConverter"